FROM golang:1.24.6-alpine3.22 AS builder

WORKDIR /app
COPY go.mod go.sum /app/
RUN go mod download
COPY . .
RUN go build -o plasma main.go

FROM scratch

COPY --from=builder /app/plasma /
CMD ["/plasma"]
