services:
  web:
    image: nginx:alpine
    ports:
      - "8008:80"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  nginx-conf:
    driver: local
