services:
  web:
    image: nginx:alpine
    ports:
      - "8008:80"
    volumes:
      - nginx_vol:/usr/share/nginx/html
      - /tmp/data:/usr/share/nginx/test
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  nginx_vol:
    driver: local
