name: Build and Push plasma-server to GHCR

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace version from develop to tag in version/version.go
        run: |
          sed -i "s/develop/${GITHUB_REF_NAME}/g" version/version.go

      - name: Build and push Docker image
        run: |
          IMAGE="ghcr.io/pgulb/plasma:${GITHUB_REF_NAME}"
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 -t $IMAGE .
